### ISSUE TITLE
መልክአ፡ ገላውዴዎስ፡

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Works#253]
Image of Gälawǝdewos (Claudius), መልክአ፡ ገላውዴዎስ፡ is identified as a work without Chaine reference number in EMIP 487. Just wondering if I should create a work file for this. I'm very much aware that we shouldn't be creating work files without careful consideration, so perhaps we also need to develop a proper approach to dealing with things like this as they arise in the EMIP collection? 
I attach images of the folios from EMIP 487 that include this work. It is split between the beginning and the end of the manuscript - apologies if they are out of order, but the image numbers give the correct order
![EMIP00487_KaleabAddis61_008](https://user-images.githubusercontent.com/39619238/88798113-4ae75780-d19c-11ea-814a-7864e2a687ff.JPG)
![EMIP00487_KaleabAddis61_009](https://user-images.githubusercontent.com/39619238/88798116-4de24800-d19c-11ea-8953-5e88ce4ee619.JPG)
![EMIP00487_KaleabAddis61_006](https://user-images.githubusercontent.com/39619238/88798121-5044a200-d19c-11ea-9ec9-b2f37edc8ebc.JPG)
![EMIP00487_KaleabAddis61_007](https://user-images.githubusercontent.com/39619238/88798128-52a6fc00-d19c-11ea-8876-2721d7e66ebe.JPG)
![EMIP00487_KaleabAddis61_179](https://user-images.githubusercontent.com/39619238/88798133-55a1ec80-d19c-11ea-8f40-3e6093f86e9e.JPG)
![EMIP00487_KaleabAddis61_178](https://user-images.githubusercontent.com/39619238/88798134-56d31980-d19c-11ea-879a-747e37c8ff9f.JPG)

**Comment by thea-m** [comment]
Thank you!
The correct new workflow is indeed to open an issue for quick discussion before creating any work, just as this one. Once the creation is agreed upon, a new ID can be created, and the same people who were involved in the issue can be assigned to review it (I would suggest, in addition to me, @DenisNosnitsin1970 and @DariaElagina. Of course we don't always work all at the same time, so that should increase the chances of a quick response). If you go on "new issue" and chose the "New work creation template", you'll get all the appropriate labels automatically.

Regarding the malk' - yes, it seems to me as well that no ID exists for this one yet, so a new one should be created. Can you create IDs or would you like me to do it?

**Comment by Ralph-Lee-UK** [comment]
I'll create it happily, and noted that I'll run this by the other two as well in future cases. I should probably ask you to approve the pull request when it is made - then you can check that what I have done is correct.  Would that make sense?

**Comment by thea-m** [comment]
Yes, perfect. I only saw now that this issue was created in the work repository. If it would not trouble you, could you create future issues in the documentation repository, where you will also find the work creation template? https://github.com/BetaMasaheft/Documentation/issues

**Comment by Ralph-Lee-UK** [comment]
Noted! Thanks so much for your help. There may be a few of these coming in the next few weeks, so it's good to know the correct way of doing this.
